# Generated by Django 2.1.2 on 2018-10-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='static/dish/images/disaster.jpg', max_length=500, upload_to='static/images/disasters')),
                ('state', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('drought', 'DROUGHT'), ('avalanche', 'AVALANCHE'), ('wildfire', 'WILDFIRE'), ('flood', 'FLOOD'), ('earthquake', 'EARTHQUAKE'), ('tsunami', 'TSUNAMI'), ('storm', 'STORMS')], max_length=2)),
                ('date_started', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='static/dish/images/person.jpg', max_length=500, upload_to='static/images/persons')),
                ('specific_characteristics', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300, null=True)),
                ('clothing', models.CharField(max_length=300)),
                ('age_estimate', models.IntegerField()),
                ('height', models.IntegerField()),
                ('alive', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('found', 'FOUND'), ('missing', 'MISSING'), ('identified', 'IDENTIFIED')], max_length=20)),
                ('blood_group', models.CharField(choices=[('O+', 'O-positive'), ('O-', 'O-negative'), ('A+', 'A-positive'), ('A-', 'A-negative'), ('B+', 'B-positive'), ('B-', 'B-negative'), ('AB+', 'AB-positive'), ('AB-', 'AB-negative'), ('X', 'UNKNOWN')], max_length=2)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=11)),
                ('disaster', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='FindThem.Disaster')),
            ],
        ),
    ]
