# Generated by Django 2.1.2 on 2018-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindThem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('drought', 'Drought'), ('avalanche', 'Avalanche'), ('wildfire', 'Wildfire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('tsunami', 'Tsunami'), ('storm', 'Storm')], max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('X', 'Unknown')], max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(default='Fdss', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, default='dgsdg', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('missing', 'Missing'), ('identified', 'Identified')], max_length=20),
        ),
    ]
