# Generated by Django 2.1.2 on 2018-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindThem', '0003_auto_20181023_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('drought', 'Drought'), ('avalanche', 'Avalanche'), ('wildfire', 'Wildfire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('tsunami', 'Tsunami'), ('storm', 'Storm')], max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(default='India', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=30),
            preserve_default=False,
        ),
    ]
